# Generated by Django 4.0.5 on 2022-07-05 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.IntegerField()),
                ('course_description', models.CharField(max_length=100)),
                ('duration', models.FloatField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to='teacher')),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_code', models.CharField(max_length=100)),
                ('lesson_number', models.CharField(max_length=50, null=True)),
                ('lesson_title', models.CharField(max_length=50, null=True)),
                ('lesson_description', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, upload_to='teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
            ],
        ),
    ]
