# Generated by Django 4.0.5 on 2022-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
