# Generated by Django 4.0.5 on 2022-07-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
