# Generated by Django 4.0.5 on 2022-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, unique=True, upload_to='school'),
        ),
    ]
