# Generated by Django 4.0.5 on 2022-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_myuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='index_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
